version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm install

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm test
      - run: npm lint  
  Analyse:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm analyse
workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - Analyse:
          requires:
            - test

         

